/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import { ExternalLink } from "lucide-react";
import Link from "next/link";
import { EmptyState, PageHero, PublicErrorState } from "@/components/public/ui";
import { getContentBlocks, getSponsors } from "@/lib/public/client";
import { CONTENT_KEYS, contentByKey } from "@/lib/public/content";
export const metadata:Metadata={title:"Sponsors",description:"Meet the community partners who support youth athletics."};
export default async function SponsorsPage(){try{const [sponsors,blocks]=await Promise.all([getSponsors(),getContentBlocks()]);const intro=contentByKey(blocks).get(CONTENT_KEYS.sponsorsIntro);return <><PageHero eyebrow="Community partners" title={intro?.title??"Support that keeps athletes moving"} summary={intro?.body}/><section className="content-section"><div className="site-container">{sponsors.length?<div className="sponsor-grid">{sponsors.map(sponsor=><article className="sponsor-card" key={sponsor.slug}><div className="sponsor-logo">{sponsor.logoUrl?/* eslint-disable-next-line @next/next/no-img-element */<img src={sponsor.logoUrl} alt={`${sponsor.name} logo`}/>:<span>{sponsor.name}</span>}</div><span className="tag">{sponsor.tier}</span><h2>{sponsor.name}</h2>{sponsor.description&&<p>{sponsor.description}</p>}{sponsor.websiteUrl&&<a className="text-link" href={sponsor.websiteUrl} target="_blank" rel="noreferrer noopener">Visit website<ExternalLink size={15} aria-hidden="true"/></a>}</article>)}</div>:<EmptyState title="Sponsor profiles are coming soon" message="Active community partners will be recognized here."/>}</div></section><section className="cta-band"><div className="site-container"><div><h2>Interested in supporting the team?</h2><p>Start a sponsorship conversation with the club.</p></div><Link className="button button-light" href="/contact">Contact us</Link></div></section></>;}catch{return <><PageHero title="Sponsors"/><div className="site-container content-section"><PublicErrorState/></div></>;}}
