<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/El1teSpr1ntTrack.Infrastructure/El1teSpr1ntTrack.Infrastructure.csproj" />
    <ProjectReference Include="../../src/El1teSpr1ntTrack.Core/El1teSpr1ntTrack.Core.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup><InternalsVisibleTo Include="El1teSpr1ntTrack.IntegrationTests" /></ItemGroup>
</Project>
