import type { Metadata } from "next";
import { Camera, ExternalLink, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import Link from "next/link";
import { ContactForm } from "@/components/public/contact-form";
import { PageHero } from "@/components/public/ui";
import { fallbackSettings, getSiteSettings } from "@/lib/public/client";
import { BRAND } from "@/lib/public/site";
export const metadata:Metadata={title:"Contact",description:"Contact the club about programs, registration, sponsorship, or volunteering."};
export default async function ContactPage(){const settings=await getSiteSettings().catch(()=>fallbackSettings);const address=[settings.addressLine1,settings.addressLine2,[settings.city,settings.state,settings.zipCode].filter(Boolean).join(", ")].filter(Boolean).join("\n");const facebookUrl=settings.facebookUrl??BRAND.facebookUrl;const instagramUrl=settings.instagramUrl??BRAND.instagramUrl;return <><PageHero eyebrow="Contact" title="Get In" accent="Touch" summary="Ask about programs, registration, partnerships, volunteering, or anything else we can help with."/><section className="content-section"><div className="site-container contact-layout"><aside><p className="eyebrow">Club contact</p><h2>Reach the team</h2><p>Choose the inquiry type that best fits your question. A club administrator can review your message securely.</p><div className="contact-details">{settings.contactEmail&&<a href={`mailto:${settings.contactEmail}`}><Mail aria-hidden="true"/><span><strong>Email</strong>{settings.contactEmail}</span></a>}{settings.phoneNumber&&<a href={`tel:${settings.phoneNumber}`}><Phone aria-hidden="true"/><span><strong>Phone</strong>{settings.phoneNumber}</span></a>}{address&&<p><MapPin aria-hidden="true"/><span><strong>Address</strong>{address}</span></p>}</div><div className="social-panel"><h3>Follow along</h3><div className="social-links"><a href={facebookUrl} target="_blank" rel="noreferrer noopener" aria-label="El1te Spr1nt Athlet1cs on Facebook"><MessageCircle aria-hidden="true"/></a><a href={instagramUrl} target="_blank" rel="noreferrer noopener" aria-label="El1te Spr1nt Athlet1cs on Instagram"><Camera aria-hidden="true"/></a><a href={BRAND.shopUrl} target="_blank" rel="noreferrer noopener" aria-label="Open the El1te Spr1nt Athlet1cs shop"><ExternalLink aria-hidden="true"/></a></div></div><div className="notice"><h3>Registration questions</h3><p>Use the Registration inquiry type in the form so your message is routed clearly.</p><Link className="text-link" href="/registration">Review registration info</Link></div></aside><div className="contact-form-panel"><p className="eyebrow">Send a message</p><h2>Tell us what you need</h2><ContactForm/></div></div></section></>;}
