"use client";

import { useRouter } from "next/navigation";
import { Checkbox, Field, fieldError, FormActions, FormNotice, FormSection, SelectField, TextArea } from "./form-controls";
import { useAdminMutation } from "@/lib/admin/use-admin-mutation";
import { EVENT_TYPES, type AdminEvent, type EventType, type EventWriteRequest } from "@/lib/admin/types";
import { iso, nullable, text, toLocalDateTime, validateEvent } from "@/lib/admin/validation";

export function EventForm({ item }: { item?: AdminEvent }) { const router = useRouter(); const mutation = useAdminMutation<AdminEvent>();
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const request: EventWriteRequest = { title: text(data.get("title")), eventType: text(data.get("eventType")) as EventType, startDateTimeUtc: iso(data.get("startDateTimeUtc")) ?? "", endDateTimeUtc: iso(data.get("endDateTimeUtc")), locationName: text(data.get("locationName")), address: nullable(data.get("address")), description: text(data.get("description")), registrationUrl: nullable(data.get("registrationUrl")), imageUrl: nullable(data.get("imageUrl")), isFeatured: data.get("isFeatured") === "on", isPublished: data.get("isPublished") === "on" }; const result = await mutation.save(item ? `/api/admin/events/${item.id}` : "/api/admin/events", item ? "PUT" : "POST", request, () => validateEvent(request)); if (result && !item) router.replace(`/admin/events/${result.id}/edit?saved=created`); else if (result) router.refresh(); }
  return <form onSubmit={submit} noValidate className="space-y-6"><FormNotice message={mutation.message} success={mutation.success} /><FormSection title="Event details"><Field label="Title" name="title" required maxLength={200} defaultValue={item?.title} error={fieldError(mutation.errors, "title")} /><SelectField label="Event type" name="eventType" defaultValue={item?.eventType ?? "Other"} options={EVENT_TYPES.map(value => [value, value === "TeamEvent" ? "Team event" : value === "RegistrationDeadline" ? "Registration deadline" : value])} /><Field label="Start date and time" name="startDateTimeUtc" type="datetime-local" required defaultValue={toLocalDateTime(item?.startDateTimeUtc)} error={fieldError(mutation.errors, "startDateTimeUtc")} /><Field label="End date and time (optional)" name="endDateTimeUtc" type="datetime-local" defaultValue={toLocalDateTime(item?.endDateTimeUtc)} error={fieldError(mutation.errors, "endDateTimeUtc")} /><Field label="Location name" name="locationName" required maxLength={200} defaultValue={item?.locationName} error={fieldError(mutation.errors, "locationName")} /><Field label="Address (optional)" name="address" maxLength={300} defaultValue={item?.address ?? ""} /><TextArea label="Description" name="description" rows={8} required defaultValue={item?.description} error={fieldError(mutation.errors, "description")} className="sm:col-span-2" /></FormSection><FormSection title="Publishing" description="Times are entered in your local timezone and stored as UTC. Image upload remains deferred."><Field label="Registration URL (optional)" name="registrationUrl" type="url" defaultValue={item?.registrationUrl ?? ""} error={fieldError(mutation.errors, "registrationUrl")} /><Field label="Image URL (optional)" name="imageUrl" type="url" defaultValue={item?.imageUrl ?? ""} error={fieldError(mutation.errors, "imageUrl")} /><Checkbox name="isPublished" label="Published" defaultChecked={item?.isPublished} /><Checkbox name="isFeatured" label="Featured" defaultChecked={item?.isFeatured} /></FormSection>{item && <p className="text-sm text-slate-500">Public slug: /{item.slug}. The API preserves it when the title changes.</p>}<FormActions backHref="/admin/events" backLabel="Back to events" submitting={mutation.submitting} editing={Boolean(item)} /></form>;
}
