"use client";
/* eslint-disable @next/next/no-img-element */

import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { AdminGalleryAlbum, AdminMediaAsset } from "@/lib/admin/types";
import { Checkbox, Field, FormActions, FormNotice, FormSection, SelectField, TextArea } from "./form-controls";
import { useAdminMutation } from "@/lib/admin/use-admin-mutation";

export function GalleryForm({album,assets}:{album?:AdminGalleryAlbum;assets:AdminMediaAsset[]}) {
  const router=useRouter(); const mutation=useAdminMutation<AdminGalleryAlbum>();
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const request={title:String(d.get("title")??"").trim(),slug:String(d.get("slug")??"").trim()||null,description:String(d.get("description")??"").trim(),coverMediaAssetId:String(d.get("coverMediaAssetId")??"")||null,isPublished:d.get("isPublished")==="on",eventDateUtc:d.get("eventDateUtc")?new Date(String(d.get("eventDateUtc"))).toISOString():null,displayOrder:Number(d.get("displayOrder")??0)};const result=await mutation.save(album?`/api/admin/gallery-albums/${album.id}`:"/api/admin/gallery-albums",album?"PUT":"POST",request,()=>({}));if(result&&!album)router.replace(`/admin/gallery/${result.id}/edit?saved=created`);else if(result)router.refresh();}
  return <><form onSubmit={submit} className="space-y-6"><FormNotice message={mutation.message} success={mutation.success}/><FormSection title="Album details"><Field label="Title" name="title" required maxLength={200} defaultValue={album?.title}/><Field label="Slug (optional)" name="slug" maxLength={200} defaultValue={album?.slug}/><TextArea label="Description" name="description" required rows={6} maxLength={4000} defaultValue={album?.description} className="sm:col-span-2"/><SelectField label="Cover image" name="coverMediaAssetId" defaultValue={album?.coverMediaAssetId??""} options={[["","No cover"],...assets.map(a=>[a.id,a.title] as const)]}/><Field label="Event date (optional)" name="eventDateUtc" type="datetime-local" defaultValue={toLocal(album?.eventDateUtc)}/><Field label="Display order" name="displayOrder" type="number" min={0} defaultValue={album?.displayOrder??0}/><Checkbox name="isPublished" label="Published" defaultChecked={album?.isPublished}/></FormSection><FormActions backHref="/admin/gallery" backLabel="Back to gallery" submitting={mutation.submitting} editing={Boolean(album)}/></form>{album&&<GalleryImages album={album} assets={assets}/>}</>;
}

function GalleryImages({album,assets}:{album:AdminGalleryAlbum;assets:AdminMediaAsset[]}) {
  const router=useRouter(); const [selected,setSelected]=useState(""); const [busy,setBusy]=useState(false);
  const available=assets.filter(a=>!album.media.some(m=>m.mediaAssetId===a.id));
  async function mutate(path:string,method:string,body?:unknown){setBusy(true);const r=await fetch(path,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});setBusy(false);if(!r.ok){alert((await r.json()).message??"Gallery could not be updated.");return;}router.refresh();}
  async function add(){if(!selected)return;await mutate(`/api/admin/gallery-albums/${album.id}/media`,"POST",{mediaAssetId:selected,displayOrder:album.media.length});setSelected("");}
  async function move(index:number,direction:number){const ordered=[...album.media];const target=index+direction;if(target<0||target>=ordered.length)return;[ordered[index],ordered[target]]=[ordered[target],ordered[index]];await mutate(`/api/admin/gallery-albums/${album.id}/media/order`,"PUT",{items:ordered.map((item,i)=>({albumMediaId:item.id,displayOrder:i}))});}
  return <section className="mt-8 border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">Album images</h2><div className="mt-4 flex gap-2"><select value={selected} onChange={e=>setSelected(e.target.value)} className="min-h-11 min-w-0 flex-1 border border-slate-300 px-3"><option value="">Choose active media</option>{available.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select><button type="button" disabled={!selected||busy} onClick={add} className="inline-flex items-center gap-2 bg-track-red px-4 font-bold text-white"><Plus size={17}/>Add</button></div><div className="mt-5 grid gap-3">{album.media.map((item,index)=><article key={item.id} className="grid grid-cols-[80px_1fr_auto] items-center gap-3 border border-slate-200 p-3"><img src={item.publicUrl} alt={item.altTextOverride??item.altText} className="h-16 w-20 object-cover"/><div className="min-w-0"><h3 className="truncate font-bold">{item.title}</h3><p className="text-xs text-slate-500">{item.captionOverride??item.caption??"No caption"}</p></div><div className="flex gap-1"><IconButton label="Move up" onClick={()=>move(index,-1)} disabled={index===0||busy}><ArrowUp size={16}/></IconButton><IconButton label="Move down" onClick={()=>move(index,1)} disabled={index===album.media.length-1||busy}><ArrowDown size={16}/></IconButton><IconButton label="Remove" onClick={()=>mutate(`/api/admin/gallery-albums/${album.id}/media/${item.id}`,"DELETE")} disabled={busy}><Trash2 size={16}/></IconButton></div><details className="col-span-full"><summary className="cursor-pointer text-sm font-bold">Album-specific metadata</summary><form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void mutate(`/api/admin/gallery-albums/${album.id}/media/${item.id}`,"PUT",{mediaAssetId:item.mediaAssetId,altTextOverride:String(d.get("altTextOverride")??"").trim()||null,captionOverride:String(d.get("captionOverride")??"").trim()||null,displayOrder:item.displayOrder});}}><label className="text-sm font-bold">Alt text override<input name="altTextOverride" maxLength={500} defaultValue={item.altTextOverride??""} className="mt-1 min-h-11 w-full border border-slate-300 px-3"/></label><label className="text-sm font-bold">Caption override<input name="captionOverride" maxLength={1000} defaultValue={item.captionOverride??""} className="mt-1 min-h-11 w-full border border-slate-300 px-3"/></label><button disabled={busy} className="min-h-10 bg-track-ink px-4 text-sm font-bold text-white sm:col-span-2 sm:justify-self-end">Save image metadata</button></form></details></article>)}{!album.media.length&&<p className="py-5 text-sm text-slate-500">No images in this album yet.</p>}</div></section>;
}
function IconButton({label,onClick,disabled,children}:{label:string;onClick:()=>void;disabled:boolean;children:React.ReactNode}){return <button type="button" title={label} aria-label={label} onClick={onClick} disabled={disabled} className="h-9 w-9 border border-slate-300 disabled:opacity-30">{children}</button>}
function toLocal(value?:string|null){if(!value)return"";const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
