import Link from "next/link";
import { Search, X } from "lucide-react";

export function FilterText({ label = "Search", name = "search", value, placeholder }: { label?: string; name?: string; value?: string; placeholder?: string }) { return <label className="text-sm font-bold text-track-ink">{label}<input name={name} type={name.toLowerCase().includes("date") ? "date" : "search"} defaultValue={value} placeholder={placeholder} className="mt-2 min-h-10 w-full border border-slate-300 px-3 font-normal outline-none focus:border-track-red" /></label>; }
export function FilterSelect({ label, name, value, options }: { label: string; name: string; value?: string; options: readonly (readonly [string, string])[] }) { return <label className="text-sm font-bold text-track-ink">{label}<select name={name} defaultValue={value ?? ""} className="mt-2 min-h-10 w-full border border-slate-300 bg-white px-3 font-normal outline-none focus:border-track-red">{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
export function FilterActions({ clearHref, filtered }: { clearHref: string; filtered: boolean }) { return <div className="flex gap-2"><button className="inline-flex min-h-10 items-center gap-2 bg-track-ink px-4 text-sm font-bold text-white"><Search size={17} />Apply</button>{filtered && <Link href={clearHref} className="inline-flex h-10 w-10 items-center justify-center border border-slate-300 text-slate-600" aria-label="Clear filters" title="Clear filters"><X size={18} /></Link>}</div>; }
export function Badge({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "neutral" | "green" | "blue" | "amber" | "red" }) { const styles = { neutral: "bg-slate-200 text-slate-800", green: "bg-emerald-100 text-emerald-800", blue: "bg-blue-100 text-blue-800", amber: "bg-amber-100 text-amber-900", red: "bg-red-100 text-red-800" }; return <span className={`inline-flex min-h-7 items-center px-2 text-xs font-bold ${styles[tone]}`}>{children}</span>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><h2 className="text-lg font-black text-track-ink">{title}</h2><p className="mt-2 text-sm text-slate-600">{description}</p></div>; }
export function formatDate(value?: string | null, time = true) { return value ? new Intl.DateTimeFormat(undefined, time ? { dateStyle: "medium", timeStyle: "short" } : { dateStyle: "medium" }).format(new Date(value)) : "Not set"; }
