"use client";

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { LoaderCircle, Power, Trash2, X } from "lucide-react";

export function ResourceActionButton({ endpoint, name, mode, redirectTo }: { endpoint: string; name: string; mode: "delete" | "deactivate"; redirectTo?: string }) {
  const router = useRouter(); const dialog = useRef<HTMLDialogElement>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const destructive = mode === "delete"; const Icon = destructive ? Trash2 : Power;
  async function confirm() { setBusy(true); setError(null); try { const response = await fetch(endpoint, { method: "DELETE" }); if (response.status === 401) { window.location.assign("/api/admin-session/logout?reason=expired"); return; } if (response.status === 403) { window.location.assign("/admin/access-denied"); return; } if (!response.ok) { const body = await response.json() as { message?: string }; setError(body.message ?? `The item could not be ${destructive ? "deleted" : "deactivated"}.`); return; } dialog.current?.close(); if (redirectTo) router.replace(redirectTo); else router.refresh(); } catch { setError("The request failed. Try again."); } finally { setBusy(false); } }
  return <><button type="button" onClick={() => dialog.current?.showModal()} className="inline-flex h-9 w-9 items-center justify-center border border-slate-300 text-slate-600 hover:border-track-red hover:text-track-red focus:outline-none focus:ring-2 focus:ring-track-red" aria-label={`${destructive ? "Delete" : "Deactivate"} ${name}`} title={destructive ? "Delete" : "Deactivate"}><Icon size={17} /></button><dialog ref={dialog} onClose={() => setError(null)} className="w-[min(92vw,480px)] border-0 p-0 shadow-2xl backdrop:bg-black/55"><div className="border-t-4 border-track-red bg-white p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-black text-track-ink">{destructive ? "Delete permanently?" : "Deactivate this item?"}</h2><p className="mt-2 text-sm leading-6 text-slate-600"><strong>{name}</strong> {destructive ? "will be permanently deleted. This cannot be undone." : "will stop appearing publicly. You can reactivate it by editing the record."}</p></div><button type="button" onClick={() => dialog.current?.close()} className="p-2 text-slate-500" aria-label="Close confirmation"><X size={20} /></button></div>{error && <p role="alert" className="mt-4 bg-red-50 px-3 py-2 text-sm font-semibold text-red-800">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" disabled={busy} onClick={() => dialog.current?.close()} className="min-h-10 border border-slate-300 px-4 text-sm font-bold">Cancel</button><button type="button" disabled={busy} onClick={confirm} className="inline-flex min-h-10 items-center gap-2 bg-track-red px-4 text-sm font-bold text-white disabled:opacity-60">{busy ? <LoaderCircle size={17} className="animate-spin" /> : <Icon size={17} />}{busy ? "Working..." : destructive ? "Delete permanently" : "Deactivate"}</button></div></div></dialog></>;
}
