import Link from "next/link";
import { ArrowLeft, Mail, Phone } from "lucide-react";
import { PageHeader } from "@/components/admin/page-header";
import { StoreOrderActions } from "@/components/admin/store-order-actions";
import { requireAdminUser } from "@/lib/admin/auth";
import { getAdminItem } from "@/lib/admin/page-data";
import type { AdminStoreOrder } from "@/lib/admin/types";

export default async function StoreOrderPage({ params }: { params: Promise<{id:string}> }) {
  const {id}=await params;
  const [order,user]=await Promise.all([getAdminItem<AdminStoreOrder>(`/api/admin/store/orders/${id}`),requireAdminUser()]);
  return <><PageHeader title={order.orderReference} description={`${order.status.replace(/([a-z])([A-Z])/g,"$1 $2")} · ${order.paymentStatus} · ${money(order.totalMinor,order.currency)}`}/><Link href="/admin/store/orders" className="mb-5 inline-flex items-center gap-2 text-sm font-black text-track-red print:hidden"><ArrowLeft size={16}/>Back to orders</Link>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="space-y-6"><section className="border-t-4 border-track-ink bg-white p-5"><div className="grid gap-5 md:grid-cols-2"><div><p className="text-xs font-black uppercase tracking-widest text-track-red">Adult buyer</p><h2 className="mt-1 text-2xl font-black">{order.customerName}</h2><a href={`mailto:${order.customerEmail}`} className="mt-3 flex items-center gap-2 text-sm"><Mail size={16}/>{order.customerEmail}</a><a href={`tel:${order.customerPhone}`} className="mt-2 flex items-center gap-2 text-sm"><Phone size={16}/>{order.customerPhone}</a></div><div><p className="text-xs font-black uppercase tracking-widest text-track-red">Handoff context</p><p className="mt-2 text-sm leading-6 text-slate-600">{order.athleteTeamNote ?? "No athlete or team note supplied."}</p>{order.fulfillmentNote && <p className="mt-2 text-sm font-bold">{order.fulfillmentNote}</p>}</div></div></section>
      <section className="border-t-4 border-track-red bg-white p-5"><h2 className="text-xl font-black">Production sheet</h2><div className="mt-4 divide-y">{order.items.map(item=><article key={item.id} className="grid gap-3 py-4 md:grid-cols-[1fr_auto]"><div><h3 className="font-black">{item.quantity} × {item.productName}</h3><p className="text-sm text-slate-600">{item.variantName} · SKU {item.sku}</p><dl className="mt-2 flex flex-wrap gap-2">{item.configuration.map(value=><div key={`${value.label}-${value.value}`} className="bg-slate-100 px-2 py-1 text-xs"><dt className="inline font-black">{value.label}: </dt><dd className="inline">{value.value}</dd></div>)}</dl></div><strong>{money(item.lineTotalMinor,order.currency)}</strong></article>)}</div><dl className="ml-auto mt-4 max-w-sm space-y-2 border-t pt-4"><div className="flex justify-between"><dt>Subtotal</dt><dd>{money(order.subtotalMinor,order.currency)}</dd></div><div className="flex justify-between"><dt>Tax</dt><dd>{money(order.taxMinor,order.currency)}</dd></div><div className="flex justify-between text-lg font-black"><dt>Total</dt><dd>{money(order.totalMinor,order.currency)}</dd></div></dl></section>
      <section className="border-t-4 border-track-ink bg-white p-5"><h2 className="text-xl font-black">Order timeline</h2><ol className="mt-4 space-y-4"><li><strong>Checkout started</strong><time className="block text-xs text-slate-500">{new Date(order.createdAtUtc).toLocaleString()}</time></li>{order.timeline.map((item,index)=><li key={`${item.createdAtUtc}-${index}`}><strong>{item.toStatus.replace(/([a-z])([A-Z])/g,"$1 $2")}</strong>{item.note&&<p className="text-sm text-slate-600">{item.note}</p>}<time className="block text-xs text-slate-500">{new Date(item.createdAtUtc).toLocaleString()}</time></li>)}</ol>{order.notes.length>0&&<div className="mt-5 border-t pt-4"><h3 className="font-black">Internal notes</h3>{order.notes.map(note=><article className="mt-2 bg-amber-50 p-3 text-sm" key={note.id}>{note.note}<time className="mt-1 block text-xs text-slate-500">{new Date(note.createdAtUtc).toLocaleString()}</time></article>)}</div>}</section>
      {(order.refunds.length>0||order.emails.length>0)&&<section className="border-t-4 border-slate-500 bg-white p-5"><h2 className="text-xl font-black">Financial and email history</h2>{order.refunds.map(refund=><p className="mt-3 text-sm" key={refund.id}><strong>{refund.status} refund {money(refund.amountMinor,order.currency)}</strong> — {refund.reason}</p>)}{order.emails.map(email=><p className="mt-2 text-sm" key={email.id}><strong>{email.templateName}</strong> — {email.status}</p>)}</section>}
    </div><StoreOrderActions order={order} superAdmin={user.role==="SuperAdmin"}/></div></>;
}
function money(value:number,currency:string){return new Intl.NumberFormat("en-US",{style:"currency",currency}).format(value/100);}
