/* eslint-disable @next/next/no-img-element -- CMS media can use administrator-configured external hosts. */
import type { Metadata } from "next";
import { Medal, Timer, Users } from "lucide-react";
import Link from "next/link";
import { PageHero, PublicErrorState } from "@/components/public/ui";
import { getContentBlocks } from "@/lib/public/client";
import { CONTENT_KEYS, contentByKey } from "@/lib/public/content";
export const metadata: Metadata = { title: "Programs", description: "Explore youth track and field development programs." };
export default async function ProgramsPage() { try { const block=contentByKey(await getContentBlocks()).get(CONTENT_KEYS.homePrograms); return <><PageHero eyebrow="Programs" title={block?.title ?? "Training For"} accent={block?.title ? undefined : "Every Step"} summary={block?.body} />{block?.imageUrl&&<div className="programs-feature-media"><div className="site-container"><img src={block.imageUrl} alt={`Athletes participating in ${block.title}`} /></div></div>}<section className="content-section"><div className="site-container program-grid detailed"><article><Timer /><h2>Track and field training</h2><p>Foundational instruction supports safe movement, sprint mechanics, conditioning, and event awareness.</p></article><article><Users /><h2>Age-group development</h2><p>Training is structured to help young athletes grow at an appropriate pace while learning team habits.</p></article><article><Medal /><h2>Competition preparation</h2><p>Meet preparation helps athletes understand routines, goals, sportsmanship, and confident competition.</p></article></div></section><section className="cta-band"><div className="site-container"><div><h2>Questions about the right fit?</h2><p>Reach out for current season and eligibility information.</p></div><Link className="button button-light" href="/contact">Contact us</Link></div></section></>; } catch { return <><PageHero title="Training" accent="Programs" /><div className="site-container content-section"><PublicErrorState /></div></>; } }
