import { AnnouncementForm } from "@/components/admin/announcement-form";
import { PageHeader } from "@/components/admin/page-header";

export default function NewAnnouncementPage() { return <><PageHeader title="Create announcement" description="Create a draft or publish a new update. The public slug is generated by the API." /><AnnouncementForm /></>; }
